Add new design for header and footer.
plumerai/blog pull request #25
Opened 2021-06-09 15:24 UTC by AdamHillier

2021-06-09 15:26 UTC, AdamHillier commented on themes/plumerai-blog/static/js/header.js
> +!function(){var t,e,s={241:function(t,e,s){"use strict";var i,a,r,n,h,o=s(208),l=s.n(o),p=JSON.parse('{"v":"5.6.10","fr":25,"ip":0,"op":8,"w":32,"h":32,"nm":"Menu-Icon_X","ddd":0,"assets":[],"layers"
I appreciate that this is a bit ugly - it's the minified JS produced by webpack for the header/navbar animations on the main website.

But, short of setting up webpack on the blog too, I think this will do. It's unlikely to be updated often (or ever).

2021-06-09 15:34 UTC, lgeiger requested changes

2021-06-09 15:34 UTC, lgeiger commented on themes/plumerai-blog/layouts/partials/header.html
> +        <img id="logo" src="/images/logo_wordmark.svg" alt="Plumerai logo" />
I just noticed that the antialiasing on my 1440p monitor on Chrome looks pretty bad. But this is the case for the main page as well. On my small macbook retina screen this is less of a problem though. I wonder if that's something the designers could fix.

2021-06-09 15:34 UTC, lgeiger commented on themes/plumerai-blog/layouts/partials/header.html
> +        <img id="logo" src="/images/logo_wordmark.svg" alt="Plumerai logo" />
Actually this seems to make anti aliasing a bit better.
```suggestion
        <img id="logo-blog" src="/images/logo_wordmark_blog.svg" alt="Plumerai blog logo" />
```

2021-06-09 15:34 UTC, lgeiger commented on themes/plumerai-blog/layouts/partials/header.html
> +                <li><a href="https://plumerai.com">Visit Plumerai.com</a></li>
How do you feel about `plumerai.com` vs `Plumerai.com`? I think as a website link I kind of prefer the former.

2021-06-14 13:52 UTC, AdamHillier commented on themes/plumerai-blog/layouts/partials/header.html
> +        <img id="logo" src="/images/logo_wordmark.svg" alt="Plumerai logo" />
Yeah so the issue here is that I'm overlaying two identical(ish) svgs on top of each other, because I need one part of it to have a high z-index and another part to have a small z-index. I'll look for a better solution though :+1:

2021-06-14 13:53 UTC, AdamHillier commented on themes/plumerai-blog/layouts/partials/header.html
> +        <img id="logo" src="/images/logo_wordmark.svg" alt="Plumerai logo" />
Yeah, unfortunately the two images are a solution for something else 😆 Will try and find another way of doing it.

2021-06-14 13:53 UTC, AdamHillier commented on themes/plumerai-blog/layouts/partials/header.html
> +                <li><a href="https://plumerai.com">Visit Plumerai.com</a></li>
The designers seem to want to go with the capitalised version - I'm easy either way. cc @rnusselder thoughts?

2021-06-14 16:59 UTC, AdamHillier commented on themes/plumerai-blog/layouts/partials/header.html
> +        <img id="logo" src="/images/logo_wordmark.svg" alt="Plumerai logo" />
@lgeiger I've now updated the approach, could you take another look to see if the problem is still there?

2021-06-14 17:05 UTC, lgeiger commented on themes/plumerai-blog/layouts/partials/header.html
> +        <img id="logo" src="/images/logo_wordmark.svg" alt="Plumerai logo" />
That looks much better.
Personally I think it is still not the nicest looking aliasing on a 1440p (non-retina) monitor, but that's due to the font and is also present in the other titles and headers. So if we stick with this font I think that's as good as it get's in terms of readability.

2021-06-14 17:08 UTC, lgeiger approved these changes

2021-06-15 13:21 UTC, merged